# See https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  - script: conda create --yes --quiet --name ntjoin_CI
    displayName: Create Anaconda environment

  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format clang-tidy
    displayName: Install clang-format and clang-tidy
  - script: |
      source activate ntjoin_CI
      conda install --yes --quiet --name ntjoin_CI -c conda-forge -c bioconda python=3.9 pylint samtools=1.14
      conda install --yes --quiet --name ntjoin_CI -c conda-forge -c bioconda --file requirements.txt
    displayName: Install Anaconda packages
  - script: |
      source activate ntjoin_CI
      cd bin
      pylint ntjoin_assemble.py read_fasta.py ntjoin_utils.py
      cd ..
    displayName: Run pylint
  - script: make -C src all
    displayName: Compile C++ executables
  - script: make -C src lint
    displayName: Run clang-format and clang-tidy
  - script: make -C src check
    displayName: Test C++ executables
  - script: |
      cd src/btllib
      ./compile-wrappers
    displayName: Compile btllib wrappers
  - script: |
      source activate ntjoin_CI
      conda install --yes --quiet --name ntjoin_CI -c conda-forge -c bioconda pytest bedtools samtools
      cd tests
      pytest -vs ntjoin_test.py
    displayName: Run pytests

- job: macOS_default_clang
  pool:
    vmImage: macOS-latest
  steps:
  - script: make -C src all
    displayName: Compile C++ executables with clang
  - script: make -C src check
    displayName: Test C++ executables
