/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class VectorMinimizer extends java.util.AbstractList<Indexlr.Minimizer> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorMinimizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorMinimizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_VectorMinimizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorMinimizer(Indexlr.Minimizer[] initialElements) {
    this();
    reserve(initialElements.length);

    for (Indexlr.Minimizer element : initialElements) {
      add(element);
    }
  }

  public VectorMinimizer(Iterable<Indexlr.Minimizer> initialElements) {
    this();
    for (Indexlr.Minimizer element : initialElements) {
      add(element);
    }
  }

  public Indexlr.Minimizer get(int index) {
    return doGet(index);
  }

  public Indexlr.Minimizer set(int index, Indexlr.Minimizer e) {
    return doSet(index, e);
  }

  public boolean add(Indexlr.Minimizer e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, Indexlr.Minimizer e) {
    modCount++;
    doAdd(index, e);
  }

  public Indexlr.Minimizer remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorMinimizer() {
    this(btllibJNI.new_VectorMinimizer__SWIG_0(), true);
  }

  public VectorMinimizer(VectorMinimizer other) {
    this(btllibJNI.new_VectorMinimizer__SWIG_1(VectorMinimizer.getCPtr(other), other), true);
  }

  public long capacity() {
    return btllibJNI.VectorMinimizer_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    btllibJNI.VectorMinimizer_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return btllibJNI.VectorMinimizer_isEmpty(swigCPtr, this);
  }

  public void clear() {
    btllibJNI.VectorMinimizer_clear(swigCPtr, this);
  }

  public VectorMinimizer(int count, Indexlr.Minimizer value) {
    this(btllibJNI.new_VectorMinimizer__SWIG_2(count, Indexlr.Minimizer.getCPtr(value), value), true);
  }

  private int doSize() {
    return btllibJNI.VectorMinimizer_doSize(swigCPtr, this);
  }

  private void doAdd(Indexlr.Minimizer x) {
    btllibJNI.VectorMinimizer_doAdd__SWIG_0(swigCPtr, this, Indexlr.Minimizer.getCPtr(x), x);
  }

  private void doAdd(int index, Indexlr.Minimizer x) {
    btllibJNI.VectorMinimizer_doAdd__SWIG_1(swigCPtr, this, index, Indexlr.Minimizer.getCPtr(x), x);
  }

  private Indexlr.Minimizer doRemove(int index) {
    return new Indexlr.Minimizer(btllibJNI.VectorMinimizer_doRemove(swigCPtr, this, index), true);
  }

  private Indexlr.Minimizer doGet(int index) {
    return new Indexlr.Minimizer(btllibJNI.VectorMinimizer_doGet(swigCPtr, this, index), false);
  }

  private Indexlr.Minimizer doSet(int index, Indexlr.Minimizer val) {
    return new Indexlr.Minimizer(btllibJNI.VectorMinimizer_doSet(swigCPtr, this, index, Indexlr.Minimizer.getCPtr(val), val), true);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    btllibJNI.VectorMinimizer_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
