/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package btllib;

public class VectorUint64t extends java.util.AbstractList<java.math.BigInteger> implements java.util.RandomAccess {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VectorUint64t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorUint64t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        btllibJNI.delete_VectorUint64t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorUint64t(java.math.BigInteger[] initialElements) {
    this();
    reserve(initialElements.length);

    for (java.math.BigInteger element : initialElements) {
      add(element);
    }
  }

  public VectorUint64t(Iterable<java.math.BigInteger> initialElements) {
    this();
    for (java.math.BigInteger element : initialElements) {
      add(element);
    }
  }

  public java.math.BigInteger get(int index) {
    return doGet(index);
  }

  public java.math.BigInteger set(int index, java.math.BigInteger e) {
    return doSet(index, e);
  }

  public boolean add(java.math.BigInteger e) {
    modCount++;
    doAdd(e);
    return true;
  }

  public void add(int index, java.math.BigInteger e) {
    modCount++;
    doAdd(index, e);
  }

  public java.math.BigInteger remove(int index) {
    modCount++;
    return doRemove(index);
  }

  protected void removeRange(int fromIndex, int toIndex) {
    modCount++;
    doRemoveRange(fromIndex, toIndex);
  }

  public int size() {
    return doSize();
  }

  public VectorUint64t() {
    this(btllibJNI.new_VectorUint64t__SWIG_0(), true);
  }

  public VectorUint64t(VectorUint64t other) {
    this(btllibJNI.new_VectorUint64t__SWIG_1(VectorUint64t.getCPtr(other), other), true);
  }

  public long capacity() {
    return btllibJNI.VectorUint64t_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    btllibJNI.VectorUint64t_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return btllibJNI.VectorUint64t_isEmpty(swigCPtr, this);
  }

  public void clear() {
    btllibJNI.VectorUint64t_clear(swigCPtr, this);
  }

  public VectorUint64t(int count, java.math.BigInteger value) {
    this(btllibJNI.new_VectorUint64t__SWIG_2(count, value), true);
  }

  private int doSize() {
    return btllibJNI.VectorUint64t_doSize(swigCPtr, this);
  }

  private void doAdd(java.math.BigInteger x) {
    btllibJNI.VectorUint64t_doAdd__SWIG_0(swigCPtr, this, x);
  }

  private void doAdd(int index, java.math.BigInteger x) {
    btllibJNI.VectorUint64t_doAdd__SWIG_1(swigCPtr, this, index, x);
  }

  private java.math.BigInteger doRemove(int index) {
    return btllibJNI.VectorUint64t_doRemove(swigCPtr, this, index);
  }

  private java.math.BigInteger doGet(int index) {
    return btllibJNI.VectorUint64t_doGet(swigCPtr, this, index);
  }

  private java.math.BigInteger doSet(int index, java.math.BigInteger val) {
    return btllibJNI.VectorUint64t_doSet(swigCPtr, this, index, val);
  }

  private void doRemoveRange(int fromIndex, int toIndex) {
    btllibJNI.VectorUint64t_doRemoveRange(swigCPtr, this, fromIndex, toIndex);
  }

}
